[package]
name = "linux-kernel-module"
version = "0.0.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2020"

[dependencies]
bitflags = "1"

[build-dependencies]
bindgen = "0.51.0"
cc = "1.0"
shlex = "0.1"
glob = "0.3.0"